---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.19.4

inputs:
  - name: dp-import-reporter

outputs:
  - name: build

run:
  path: dp-import-reporter/ci/scripts/build.sh
